import java.util.HashMap;
import java.util.PriorityQueue;

//Class for each node in our Huffman Tree
//Internal Class to build the tree

// Jasen' code 
class HuffmanNode{
    char data;
    int frequency;
    HuffmanNode left;
    HuffmanNode right;

    //Getters and Setters

    public char getData() {
        return data;
    }

    public void setData(char data) {
        this.data = data;
    }

    public int getFrequency() {
        return frequency;
    }

    public void setFrequency(int frequency) {
        this.frequency = frequency;
    }

    public void setLeft(HuffmanNode left) {
        this.left = left;
    }

    public void setRight(HuffmanNode right) {
        this.right = right;
    }

    //Constructor
    public HuffmanNode(char data, int frequency){
        this.data = data;
        this.frequency = frequency;
    }
}

public class HuffmanEncoder {
    public String TextToCompress;
    HashMap<Character, String> codeTable = new HashMap<>();

    //Getters and Setters

    public String getTextToCompress() {
        return TextToCompress;
    }

    public void setTextToCompress(String textToCompress) {
        TextToCompress = textToCompress;
    }

    //Methods

    public HuffmanNode createTree(){
        HashMap<Character, Integer> characters = new HashMap<>(); //Create a hashmap to store the characters
        for(char c : this.TextToCompress.toCharArray()) {
            //Check if the character has already been put in the hashmap
            //If it has, Increase its frequency by 1
            if (characters.containsKey(c)) {
                characters.put(c, characters.get(c) + 1);
            }
            //If not, Add to array with initial frequency of 1
            else {
                characters.put(c, 1);
            }
        }

            //Create a Priority Queue with the smallest frequency elements towards the front
            PriorityQueue<HuffmanNode> queue =
                    new PriorityQueue<>((a,b) -> a.frequency - b.frequency);

            //Add Elements to the queue
            for(char key : characters.keySet()){
                queue.add(new HuffmanNode(key, characters.get(key)));
            }

            //Build the Tree
            while(queue.size() > 1){
                //Take the lowest 2 frequency nodes from the front
                HuffmanNode leftNode = queue.poll();
                HuffmanNode rightNode = queue.poll();

                //Create a parent of those two nodes, labeled "&" for clarity
                HuffmanNode parent = new HuffmanNode('&',leftNode.frequency+rightNode.frequency);
                parent.setLeft(leftNode);
                parent.setRight(rightNode);

                //Add node "Parent" back to the queue
                queue.add(parent);
            }
            //If there is one node left, that node will be the root
            HuffmanNode treeRoot = queue.poll();
            return treeRoot;

    }

    //Method to generate the codes for the tree
    public static void generateHuffmanCode(HuffmanNode root, StringBuilder huffmanCode, HashMap<Character,String> codes){
        //StringBuilder allows us to just append 0s and 1s as we traverse the tree
        if(root == null){
            //Means the tree is empty, and an empty tree has no codes to generate
            return;
        }

        if(root.data != '&'){
            //If the node is a child (Because all internal nodes are labeled "&", add its code to the hashMap
            codes.put(root.data, huffmanCode.toString());
        }

        //Go down the Left subtree of the node
        if(root.left != null){
            generateHuffmanCode(root.left, huffmanCode.append('0'), codes);
            huffmanCode.deleteCharAt(huffmanCode.length()-1);
        }

        //Go down the Right subtree of the node if there is no left
        if(root.right != null){
            generateHuffmanCode(root.right, huffmanCode.append('1'), codes);
            huffmanCode.deleteCharAt(huffmanCode.length()-1);
        }
    }

    //Method to create the table for the final result
    public void createTable(){
        //Create a duplicate of the hashTable generated by createTree() to use for the String
        HashMap<Character, Integer> characters = new HashMap<>(); //Create a hashmap to store the characters
        for(char c : this.TextToCompress.toCharArray()) {
            //Check if the character has already been put in the hashmap
            //If it has, Increase its frequency by 1
            if (characters.containsKey(c)) {
                characters.put(c, characters.get(c) + 1);
            }
            //If not, Add to array with initial frequency of 1
            else {
                characters.put(c, 1);
            }
        }

        HuffmanNode root = createTree();
        generateHuffmanCode(root, new StringBuilder(), codeTable);

        // Print variable bit representation (character : code) - Durga's code [this part only && creation of huffman encoder pdf file and table]
        System.out.println("Variable Bit Representation:");
        for(char key : codeTable.keySet()){
            System.out.println(key + " : " + codeTable.get(key));
        }
        System.out.println();


        System.out.println("--------------------");
        int totalBitsNeeded = 0;
        for(char key : characters.keySet()){
            int frequency = characters.get(key);
            String huffmanCode = codeTable.get(key);
            int bitsNeeded = frequency * huffmanCode.length();
            totalBitsNeeded += bitsNeeded;

            System.out.println("Character: " + key);
            System.out.println("Frequency: " + frequency);
            System.out.println("Code: " + huffmanCode);
            System.out.println("Total Bits Needed: " + bitsNeeded);
            System.out.println("--------------------");
        }
        System.out.println("Total Bits Needed: " + totalBitsNeeded);

        printTree(root, "", true);

    }

    //Method to print the tree
    public static void printTree(HuffmanNode node, String indent, boolean isRight) {
        //If the tree is empty, exit the method early
        if (node == null) return;

        //Print the node data and frequency
        System.out.println(indent + (isRight ? "R-- " : "L-- ") + node.data + ":" + node.frequency);

        //Print the connection (if applicable) to the left node
        printTree(node.left, indent + (isRight ? "    " : "|   "), false);

        //Print the connection (if applicable to the right node
        printTree(node.right, indent + (isRight ? "    " : "|   "), true);
    }
    public static void main(String[] args) {
        System.out.println("Group 1:");
        System.out.print("Durga Jhansi Yerukala (SCP203) ");
        System.out.print("Vyshanavi Yadlapati (FPL006) ");
        System.out.println("Jasen Drileck (VHA667)");
    HuffmanEncoder huff = new HuffmanEncoder(); //Set up encoder
    huff.setTextToCompress("AAAAAABBCCDDEEFFFFF"); // Text is given in rubric
    huff.createTable();


}
}
